### ISSUE TITLE
PIR V2 Red Light switch does not work.

### ISSUE THREAD

**Issue by henkbart** [mruiter/com.neo#123]
Hello,
I am using your NeoCoolcam App latest version with Homey 3.1.0
The Red Light with the PIR V2 switch on/off does not work.
I have switched them off but the still works. When i checked the settings of the device there it says 

motion_blink | false

But the devices still blink when the detect motion....
Perhaps you can help to turn them off....

**Comment by mruiter** [comment]
You need to wake up the device at the moment when you push the off setting.
So have the setting ready to apply. Wake up the device itself by quickly pressing the button inside 3 times and then press apply on the setting change in the homey app

**Comment by Sandemann** [comment]
> You need to wake up the device at the moment when you push the off setting.
> So have the setting ready to apply. Wake up the device itself by quickly pressing the button inside 3 times and then press apply on the setting change in the homey app

I had the same issue with 3 of my  (new) Neo pir sensors.
It seems that the param 10 wich is mentiont in de manual is incorrect to set the LED value on or of.
When you use param 11 it will work.
You can test this by send a (raw) config param like "11,1,0".

I dont know wich param is used by @mruiter in the homey app, maybe it is the same miss use of param 10 instead of 11.

**Comment by mruiter** [comment]
Thx for the info. Corrected in the v2.1.1 . v2.1 is still awaiting appstore approval so hope to have it online soon.
