### ISSUE TITLE
Add power plug as insecure

### ISSUE THREAD

**Issue by frankvandenhurk** [mruiter/com.neo#136]
I constantly had problems with the power plugs. Based on https://community.athom.com/t/add-z-wave-device-non-secure/12406/17 I sideloaded a modified version of your app (“includeSecure”: false) and all had been stable for weeks now. 

Would you please consider creating an insecure version of the power plug as an extra device in the official app, so I do get normal updates but still can add them as insecure?

**Comment by mruiter** [comment]
Should be implemented already a couple of app versions ago . But it never hurts to practice sideloading 😉

Verstuurd vanaf mijn iPhone

**Comment by mruiter** [comment]
That said . It complete madness that because of the lack of any real effort of athom to fix severe core issues on there implementation of zwave like secure issues and complete lack of S2 Security and Flirs support we are forced to unsecure 

Its also not true what some users say that the amount of data being transferred secure is larger and thus slower.
Yes is a bit more but the bandwith of the zwave protocol is large enough and hard to fill with normal communication.

It’s actually athom that should do the shut they are payed to do in stead of hiding and lying.

I don’t support the addition of the unsecure add. This brings the device back to the first zwave implementation .

I don’t drive a lada because they never broke down nowadays either . I drive the newest tech 



Verstuurd vanaf mijn iPhone

**Comment by frankvandenhurk** [comment]
Ah, I see it now in the code of the master, TNX!

(and I completely agree that it's a shame that the Homey Z-wave core isn't able to handle this correctly)
