### ISSUE TITLE
Temperature sensor for PIR v1

### ISSUE THREAD

**Issue by macfreek** [mruiter/com.neo#139]
Request (low priority for me): can you add support for the build in temperature sensor for the PIR v1?

The PIR v1 does have a build in temperature sensor, just like PIR v2. For some reason, some of my v1 sensors were added as a v2 (see #138), and to my surprise it did report a temperature. I briefly though I have a v2 in v1 casing, since I thought only v2 has a build in temperature sensor, but it seems that both v1 and v2 have a build in temperature sensor. See the product markings on the package at https://www.szneo.com/en/products/index.php?id=43: both products (v1 and v2) are advertised as having a temperature sensor.

**Comment by mruiter** [comment]
A real v1 does not have a temp sensor. 
V2 does .

But since Chinese people don’t spill they have put some V2 boards in the casing of a v1 . Some have a V2 firmware and some have a v1 firmware .

If they got flashed with a v1 firmware the device ids are v1 and it gets added without temp sensor . If it has V2 firmware ids it gets added with temp sensor .

I will not force a temp sensor on v1 for those few batches that have a V2 board but got flashed with v1 firmware because lots of issues will be raised by the majorities of v1 users that will say temp doesn’t report or is broken 

Verstuurd vanaf mijn iPhone
