### ISSUE TITLE
NAS-PD07

### ISSUE THREAD

**Issue by Rens-H** [mruiter/com.neo#194]
@mruiter Sorry last message was for other product I think.
Can you add the option tot edit the humidity polling time i think it takes too long to refresh for the NAS-PD07
At the moment you can only edit the motion timeout etc

![image](https://user-images.githubusercontent.com/80253879/121851330-42353c80-ccee-11eb-8b85-73ad64d3d92d.png)

**Comment by Rens-H** [comment]
@mruiter I'm experiencing problems with this device, when added it slows down the whole z-wave network. Responses are in general very slow. When removing the device everything goes back to fast responses. I talked to Athom and they say I should be talking to you as it is still in test. Can I do something for you to test ?

**Comment by mruiter** [comment]
Haha slowing down the zwave network and telling you the app could be it 
because its in test.
Guess its more that V7 firmware z-wave of homey is still in test.


Well dont believe the misleading stories Athom support tells you. They 
dont have a clue.
When zwave slows down you can send the log to ***@***.*** that you 
collected in the zwave section on developers.athom.com

Since zwave is a core process i cant access it. And the PD07 uses 
default core driver :)

Rens-H schreef op 2021-06-28 12:26:

**Comment by Rens-H** [comment]
@mruiter don't shoot de messenger ;-) . I'm trying to look for a solution,  they got my logging they cannot find anything yet. But I understand you and will take it back to Athom
