### ISSUE TITLE
PIR devices added as generic devices

### ISSUE THREAD

**Issue by markusv** [mruiter/com.neo#208]
Hi,

I just received 4 neo coolcam pir sensors. They all are added as generic devices. When added homey tels me it could not find a app for the devices. Maybe some new device ids that need to be added? here is my advanced settings screen:

![IMG_4145](https://user-images.githubusercontent.com/475663/182680840-94372813-f09b-4d58-8cf9-25d35c186c5d.jpeg)

please help!!

Regards,
Markus

**Comment by CPCremers** [comment]
I have the same problem, I have 3 new sensors, but none of them are recognized by the app. Can this be fixed so that I can use the sensors ?

**Comment by markusv** [comment]
Yes, I changed [driver.compose.json](https://github.com/mruiter/com.neo/blob/fe444b0042ddf2704f9489893586396bb3063f6d/drivers/NAS-PD02ZE/driver.compose.json#L24) for NAS-PD02ZE. Changed from “productId”: 4145, to “productId”: [4145, 4150. Installed app via cli and it works. Unfortunately I do not have permissions to contribute the fix to the app. 

The problem I now have is the new sensors report motion very slowly. They have a 10-15 seconds delay, which makes them quite useless. I do not have a solution for this yet.

**Comment by CPCremers** [comment]
That explains that yesterday the sensors still did'nt connect properly because the fix is not yet in the app.

Personally for me the delay issues for the new sensors is not a big problem because I will be using the new sensors to switch the lights off in the bedrooms after a certain time and not to switch them on. But that is just for this special use in this single case, the other sensors that I have are used to switch lights on and off. I presume that the delay issue is only for newly added sensors ?

Hopefully the issue(s) can be fixed, keep us informed if new information is available.


________________________________

**Comment by markusv** [comment]
I use them to turn on the lights. So that is why the delay makes them useless. Yes my old sensor work preferctly. They react almost immediately

**Comment by CPCremers** [comment]
The old sensors works fine also and have a quick response.

I will try the change you mentioned , perhaps it will solve my problems at this moment.

________________________________

**Comment by CPCremers** [comment]
It worked, I have succesfully changed the json file and installed the app and now the PIR devices are recognized. Markusv, thanks a lot !

**Comment by mruiter** [comment]
Added in version .16
