### ISSUE TITLE
neo coolcam zigbee 

### ISSUE THREAD

**Issue by vinsaas** [mruiter/com.neo#210]
Hi, will you add nas-ws02 water sensor, nas-ab02 siren and other zigbee devices?

**Comment by mruiter** [comment]
No , since they are just Tuya hardware rebranded in a neo case support comes with the tuya app.Since the pir , siren etc use a custom zigbee cluster specific for tuya the developers of the tuya app hasn’t yet implemented the support for these devices and many more . But he’s working on it .For now the neo rebranded zigbee power plugs work perfect with the tuya app . I also have a few 😉Verstuurd vanaf mijn iPhoneOp 14 aug. 2022 om 13:05 heeft vinsaas ***@***.***> het volgende geschreven:﻿
Hi, will you add nas-ws02 water sensor, nas-ab02 siren and other zigbee devices?
