### ISSUE TITLE
Wallplug

### ISSUE THREAD

**Issue by snakefaith** [mruiter/com.neo#212]
Hi
I bought an wallplug but I can't add it to the homey because it asks for a DSK but they didn't give me a code. I have 5 wall plugs that were added earlier and they work perfectly.
Thanks

**Comment by mruiter** [comment]
Try all zeros Verstuurd vanaf mijn iPhoneOp 6 sep. 2022 om 07:24 heeft snakefaith ***@***.***> het volgende geschreven:﻿
Hi
I bought an wallplug but I can't add it to the homey because it asks for a DSK but they didn't give me a code. I have 5 wall plugs that were added earlier and they work perfectly.
Thanks

**Comment by snakefaith** [comment]
Hi
Thanks it works. In the future, if I buy more wallplugs, will they all be 00000? there will be no  address conflict?
Thank you
