### ISSUE TITLE
SDK 3 Windows Sensor V1 not responding

### ISSUE THREAD

**Issue by meyo084** [mruiter/com.neo#232]
Hi, 

After switching to Homey 2023 with SDK 3 all modules are working great except for the window sensor v1. it shows up after (re)adding with wont give any data.. zwave seems ok.

Thanks in advance.

**Comment by mruiter** [comment]
That’s strange since it uses the default class alarm contact … does it report alarm when you look at the zwave section log on developer.athom.com ?Verstuurd vanaf mijn iPhoneOp 16 mrt. 2023 om 20:43 heeft meyo084 ***@***.***> het volgende geschreven:﻿
Hi,
After switching to Homey 2023 with SDK all modules are working great except for the window sensor v1. it shows up after (re)adding with wont give any data.. zwave seems ok.
Thanks in advance.

**Comment by mruiter** [comment]
Would it be possible for you to download the lastest verison from github (dont forget to select the v3 branche) and sideload test the app. I switched the command class to a more basic binair and not the notification. Guess something goes wrong in the sdkv3 in catching the notification

**Comment by mruiter** [comment]
fixed in 3.0.1
