### ISSUE TITLE
Neo Coolcam on Homey Pro 2023

### ISSUE THREAD

**Issue by jpperrein** [mruiter/com.neo#248]
Hi, do you have a schedule to release a compatible app for Homey Pro 2023 ?
Many thanks for your return

**Comment by mruiter** [comment]
Already there for months Verstuurd vanaf mijn iPhoneOp 25 jun. 2023 om 17:01 heeft jpperrein ***@***.***> het volgende geschreven:﻿
Hi, do you have a schedule to release a compatible app for Homey Pro 2023 ?
Many thanks for your return

**Comment by jpperrein** [comment]
Hi @mruiter 

Any Idea on how I can install the app another way than using the homey-store because I do have :
-------------------------------------------------------------------------------
**This app is not compatible with Homey Pro (Early 2023).**

This app is outdated and requires an update to work on Homey Pro (Early 2023). If you want this to happen, please contact the developer [here](https://github.com/mruiter/com.neo/issues). #
-------------------------------------------------------------------------------
And devices are not reconized.

Many thanks in advance

**Comment by mruiter** [comment]
Just add /test behind the url of the AppStore Verstuurd vanaf mijn iPhoneOp 27 jun. 2023 om 08:27 heeft jpperrein ***@***.***> het volgende geschreven:﻿
Hi @mruiter
Any Idea on how I can install the app another way than using the homey-store because I do have :
This app is not compatible with Homey Pro (Early 2023).
This app is outdated and requires an update to work on Homey Pro (Early 2023). If you want this to happen, please contact the developer here. #
And devices are not reconized.
Many thanks in advance

**Comment by jpperrein** [comment]
So simple ;-)
Works fine, great job !
Many thanks @mruiter
