### ISSUE TITLE
Neo coolcam touch switch loses settings

### ISSUE THREAD

**Issue by Domoticahuis** [mruiter/com.neo#25]
After a few days neo coolcam touch switch loses connection and settings.
it is  not recognized bij homey anymore, If you want te delete the switch, homey says it is not part of the network,  this happens with 2 different switches

**Comment by mruiter** [comment]
Strange.. does the zwave log show anything when you push the buttons ? A pair cant be really broken because the keys are in the zwave chip side of the config . So homey or driver can't be the problem. It could be a neo switch problem in there hardware . In the neo forum topic there are more switch users . Maybee if you ask there other might say hey I had that too

**Comment by mruiter** [comment]
Does this problem still happen ?

**Comment by Domoticahuis** [comment]
Sorry for the late answer. I returned it to the shop.

**Comment by mruiter** [comment]
Then i will close this issue for now as no other have reported this
