### ISSUE TITLE
Please make the app compatible with Homey Pro early 2023

### ISSUE THREAD

**Issue by WimHe** [mruiter/com.neo#263]
I have multiple devices from Neo Coolcam blicking a full migration to my new Homey

**Comment by mruiter** [comment]
then read github before you post.should considerably lower the hold up 😂Verstuurd vanaf mijn iPadOp 15 okt 2023 om 19:36 heeft Wim van den Heuvel ***@***.***> het volgende geschreven:﻿
I have multiple devices from Neo Coolcam blicking a full migration to my new Homey

**Comment by weareborg-rif** [comment]
Same for me, i've got 10 neo coolcam doorsensors. None of them is working yet. I did a full backup, s*** it was.

**Comment by mruiter** [comment]
Yes , indeed same for you 🤣Read the github issues and you will find the solution Verstuurd vanaf mijn iPhoneOp 17 okt 2023 om 11:39 heeft weareborg-rif ***@***.***> het volgende geschreven:﻿
Same for me, i've got 10 neo coolcam doorsensors. None of them is working yet. I did a full backup, s*** it was.

**Comment by mruiter** [comment]
No worries , need some fun . Guess it will be in the App Store as stable soon . Still looking for a user with the wall switches I can’t test Verstuurd vanaf mijn iPhoneOp 17 okt 2023 om 12:55 heeft weareborg-rif ***@***.***> het volgende geschreven:﻿
You are write, i didn't had my glasses on. (-:

**Comment by mruiter** [comment]
See other GitHub issues with the url to the 2023 version under test Verstuurd vanaf mijn iPhoneOp 20 okt 2023 om 14:49 heeft TomV71 ***@***.***> het volgende geschreven:﻿
Yes, an upated version for Homey Pro 2023 would be great. Just changed from Zipato to the Homey world and still some old Neo Coolcam waterleak sensors and power plugs that do not  want to connect to Homey Pro. All the rest is already transferred successfully to Homey. Great system.

**Comment by OWillekens** [comment]
> No worries , need some fun . Guess it will be in the App Store as stable soon . Still looking for a user with the wall switches I can’t test Verstuurd vanaf mijn iPhoneOp 17 okt 2023 om 12:55 heeft weareborg-rif ***@***.***> het volgende geschreven:﻿ You are write, i didn't had my glasses on. (-: —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

Hi Marco, I have now the new Homey Pro 2013 and Homey Bridge, and I wanted to add the Neo Coolcam light switches, but I can’t because the app is/was not compatible. I also have 2 older Homey Pro’s and every Neo Coolcam device works fine. How can I help you with helping me? I would love to test for you 3 Neo Coolcam light switches on my new Homey Pro 2023, so tell me what I have to do. I’ve read some GitHub comments and of course your request for a Beta test of the light switches so you could release your updated and needed Neo Coolcam app (compatible with Homey Pro 2023). Maybe I’m your guy, but I’m not an expert, just a Homey lover since day 1 and IoT supporter. Programming is not my thing. Let me know if and how I can help you, so you can help me and others with your update of your prof. app Neo Coolcam. Olivier
