### ISSUE TITLE
Neo Coolcam Siren V2 not working on Homey Pro 2023

### ISSUE THREAD

**Issue by adriaan66** [mruiter/com.neo#264]
Hoi,

Sinds ik de Homey Pro 2023 heb, heb ik inmiddels vrijwel alles aan de praat, alleen de Neo Sirene V2 krijg ik niet meer werkend.

Ik heb de Neo app al opnieuw geïnstalleerd, de test versie, maar helaas staat er alleen de optie Sirene (plaatje is de oude sirene) en daarmee kan ik de V2 sirenes helaas niet toevoegen.

Enig idee of deze functie nog terugkomt en zo ja wanneer? Anders heb ik niks meer wan de huidige sirenes en zal ik over moeten stappen op een ander merk/model.

Alvast bedankt.

Groeten,
Adriaan

—

Hi,

Since i have the new Homey Pro 2023 my Neo Siren V2 is not working anymore.

I can only select, by add device, the siren V1 and not the V2. When will the V2 version available in the app?

Regards,
Adriaan

**Comment by mruiter** [comment]
Dat is raar ,Kan je de device manufac en type ids doorsturen die je in advanced ziet als deze als generic zwave is toegevoegd ?Verstuurd vanaf mijn iPhoneOp 22 okt 2023 om 13:41 heeft adriaan66 ***@***.***> het volgende geschreven:﻿
Hoi,
Sinds ik de Homey Pro 2023 heb, heb ik inmiddels vrijwel alles aan de praat, alleen de Neo Sirene V2 krijg ik niet meer werkend.
Ik heb de Neo app al opnieuw geïnstalleerd, de test versie, maar helaas staat er alleen de optie Sirene (plaatje is de oude sirene) en daarmee kan ik de V2 sirenes helaas niet toevoegen.
Enig idee of deze functie nog terugkomt en zo ja wanneer? Anders heb ik niks meer wan de huidige sirenes en zal ik over moeten stappen op een ander merk/model.
Alvast bedankt.
Groeten,
Adriaan
—
Hi,
Since i have the new Homey Pro 2023 my Neo Siren V2 is not working anymore.
I can only select, by add device, the siren V1 and not the V2. When will the V2 version available in the app?
Regards,
Adriaan

**Comment by adriaan66** [comment]
Hoi Marco,

Dankjewel voor je snelle bericht terug. Ik heb het net nog een paar keer geprobeerd en warempel na 8x is het eindelijk gelukt, geen idee waarom het telkens niet lukte maar het lijkt te werken (sirenes zijn toegevoegd), was te vroeg met de melding. Excuses.

Bedankt voor zover.

Groet,
Adriaan


Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Marco Ruiter ***@***.***>
Verzonden: Sunday, October 22, 2023 1:51:46 PM
Aan: mruiter/com.neo ***@***.***>
CC: Adriaan Bredero ***@***.***>; Author ***@***.***>
Onderwerp: Re: [mruiter/com.neo] Neo Coolcam Siren V2 not working on Homey Pro 2023 (Issue #264)


Dat is raar ,Kan je de device manufac en type ids doorsturen die je in advanced ziet als deze als generic zwave is toegevoegd ?Verstuurd vanaf mijn iPhoneOp 22 okt 2023 om 13:41 heeft adriaan66 ***@***.***> het volgende geschreven:﻿
Hoi,
Sinds ik de Homey Pro 2023 heb, heb ik inmiddels vrijwel alles aan de praat, alleen de Neo Sirene V2 krijg ik niet meer werkend.
Ik heb de Neo app al opnieuw geïnstalleerd, de test versie, maar helaas staat er alleen de optie Sirene (plaatje is de oude sirene) en daarmee kan ik de V2 sirenes helaas niet toevoegen.
Enig idee of deze functie nog terugkomt en zo ja wanneer? Anders heb ik niks meer wan de huidige sirenes en zal ik over moeten stappen op een ander merk/model.
Alvast bedankt.
Groeten,
Adriaan
—
Hi,
Since i have the new Homey Pro 2023 my Neo Siren V2 is not working anymore.
I can only select, by add device, the siren V1 and not the V2. When will the V2 version available in the app?
Regards,
Adriaan
