### ISSUE TITLE
[Feature] Trigger card

### ISSUE THREAD

**Issue by WesRos** [mruiter/com.neo#34]
I want to have a trigger card when a switch is switched. On or Off, it doesn't matter.

**Comment by mruiter** [comment]
After a few talks the request was to make a github issue so the creation of these cards for the on/off capability get added into Homey Core.

The issue has been made and Athom is aware of the request and the need for it to get implemented.

https://github.com/athombv/homey/issues/2072

I'm clossing this issue here on the NEO app
Feel free to also show youre need for this card in the Athom Issue.

When it gets added to the homey core the cards will magicly appear when the firmware update containing the addon gets installed.
