### ISSUE TITLE
Power plug parameter #2

### ISSUE THREAD

**Issue by Patrick1610** [mruiter/com.neo#53]
Hi. 

The value of parameter #2 can only be set at 60 - 65535, while according to the manual, the parameter could be set from 1 - 65535. (https://m.koti.sk/files/coolcam/zwave/zasuvka/manual-for-power-plug-z-wave-neo.pdf)

I really need the refresh rate of 1s, so could you adjust this in the app? 

Regards, 
Patrick

**Comment by mruiter** [comment]
1 Second refresh is a nsafe value. Homey Z-Wave traffic will be flooded by these reports.
Thats way a safe lowests value has been chosen as also advised . 60 Seconds.

You can always manualy override these by sending out a Z-Wave command.
See screenshot. . These way of config is for the experts that want something different that could bring down z-wave on homey.

Please let me know if this works for you

![expertsetting](https://user-images.githubusercontent.com/17739535/40039636-718a94d4-5817-11e8-80dc-5bb2a05923c3.JPG)

**Comment by Patrick1610** [comment]
Okay, I have tried this with 10s, 5s, 2s and 1s, but I can’t seem to get this to work. 
I want to use the power plug to know when my phone is connected, even when it is fully charged (to trigger sleep/wake). A friend of mine had figured out that an iPhone connected to a 5w charger will use a little bit of power every 8 minutes, to keep the iPhone at 100%. With the interval setting at 1s, it should report this during the night, but it doesn’t seem to measure anything during the night. Any ideas on how to make this work?

![b1a70c24-5368-40aa-937f-63857b589b6f](https://user-images.githubusercontent.com/6585375/40102905-feccb910-58eb-11e8-9709-9df1c3927eb5.jpeg)
 
![fb73ef45-80e1-4b93-ae53-522c549aa5f8](https://user-images.githubusercontent.com/6585375/40102786-b682dfea-58eb-11e8-9403-5041244755b7.jpeg)

**Comment by mruiter** [comment]
This is correct. The 5 Watt isnt enough for the reporting to get activated and it does not report in.
Same as with the fibaro plugs. The electronics in the plugs need a certain drain for a certain time before they come active. I thing its 10 watts for a minute. The plug itself is about 3 watts . A constant charges of the phone will just register. But i guess trickel loading doesnt .

The parameter send reports every second will not make a difference because it then wil just send a 0w usage reports because the measuring units inside the plugs havnt activated because of the low load.

**Comment by Patrick1610** [comment]
Okay! Is that timing configurable so it is less than 10watts for a minute? 
And how does parameter 6 influence the reporting? 

Should it work with an iPad (12watt) charger?

**Comment by mruiter** [comment]
Well if the phone doesnt ask more then 5 watts the 12watt adapter will only use 5 watts .
So who knows what it will do.

Parm 6 does just like it tells.. 
You can define time based and % based reports.

So it reports every x seconds and if the power usages changes by x percent

But still it has to go above the +/- 10 watts threshold before reporting even starts seeing numbers

But since we have confirmed this is not a bug in the App.
Please take further questions to the forum topic on forum.athom.com

Github Issues are for killing bugs.
