### ISSUE TITLE
NEO wallplug doesn't connect

### ISSUE THREAD

**Issue by behgez** [mruiter/com.neo#60]
I'm using the latest version of the App, but pairing the NEO wall-plug doesn't work. Homey doesn't respond/recognize it.

Thanks!

**Comment by behgez** [comment]
Thanks for the fast response.

Well, it doesn't do anything, that is the exact problem :-) 

When I try to add the device, the app wait for a pairing activity which then times out. I press the button on the wall plug 3 times (it starts blinking fast), but Homey doesn't respond. I have the wall-plug plugged in next to Homey.

What other information do you need?

**Comment by mruiter** [comment]
Exactly this info :) 

Ok just do a remove procedure in the setting menu zwave on homey . Lets see if that sees the plug . 

If that doesnt do anything you have a) a detective plug or b) a plug thats not suited for youre region so homey and the plug work on different zwave frequenties . Every world region has zwave on a different region for example EU Asia and Us all have different zwave frequency’s

If you order came from GearBest this would be most likely since they fuck up all the time :)


Verstuurd vanaf mijn iPhone

**Comment by behgez** [comment]
Perfect, that worked. Thanks a million for the fast support!
