### ISSUE TITLE
Add PIR (NAS-PD01ZE) 869 Mhz

### ISSUE THREAD

**Issue by KarasN** [mruiter/com.neo#63]
Hi. Please add support for another one 869 Mhz devise. PIR Sensor: NAS-PD01ZE. ID: 8323
Thank you.

**Comment by mruiter** [comment]
Please provide me with the needed info to do so.
Add the device as generic device and provide the settings info highlighted in the screenshot

![info](https://user-images.githubusercontent.com/17739535/49134379-a1bfce00-f2e3-11e8-9548-2f2da94bc73c.JPG)

**Comment by mruiter** [comment]
Beta version is in the appstore . You will need to remove and rejoin he device with homey z-wave.
Please report back if it works

**Comment by KarasN** [comment]
![2018-12-19 1 43 30](https://user-images.githubusercontent.com/42243041/50187736-0e9d1580-0330-11e9-97f0-695946d93bfe.png)
Beta version don't work for me.

And now I have another one coolcam device (PIR V2 (NAS-PD02ZE)) and it has same deviceID as PIR V1
![2018-12-19 1 44 27](https://user-images.githubusercontent.com/42243041/50187988-1dd09300-0331-11e9-985b-6a930dd06e15.png)

**Comment by mruiter** [comment]
It will be added in the next beta.
Sorry to say you have a PIR with a V2 housing not V2 hardware.
If it would be V2 hardware it would have a different ID.

The V2 casing with V2 hardware would specificly state that there is a temp sensor with the pir.
At least most on ALI express promote the real V2's as WITH TEMPERATURE SENSOR !
This one is a normal V1 with the V2 casing and homey will add it as a V1 because of the ID's the electronics board
